# Generated by Django 3.2.5 on 2022-03-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('register', models.BooleanField(default=False)),
            ],
            options={
            },
        ),
    ]
