# Generated by Django 3.2.5 on 2022-03-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenLogin',
        ),
    ]
