# Generated by Django 3.2.16 on 2023-10-18 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_alter_inventaire_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'espece',
                'verbose_name_plural': 'especes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='LogCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('cart', models.TextField()),
                ('order', models.TextField(blank=True, null=True)),
                ('produit', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
                ('field', models.TextField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('produit', models.TextField()),
                ('order', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
                ('field', models.TextField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PorteGreffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'porte-greffe',
                'verbose_name_plural': 'porte-greffes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'specialité',
                'verbose_name_plural': 'specialités',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'variete',
                'verbose_name_plural': 'varietes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_bis', models.IntegerField(default=0)),
                ('stock_future', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('gaf', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.espece')),
                ('portegreffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.portegreffe')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.spec')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.variete')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('nom',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Greffons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greffons', models.IntegerField(default=0, null=True, verbose_name='Greffons')),
                ('comm', models.IntegerField(null=True, verbose_name='Pré-Commande')),
                ('objectif', models.IntegerField(default=0, null=True, verbose_name='Objectifs')),
                ('realise', models.IntegerField(default=0, null=True, verbose_name='Réalisés')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date')),
                ('rang', models.IntegerField(default=0, null=True, verbose_name='Rang')),
                ('reussi', models.IntegerField(default=0, null=True, verbose_name='Reussi')),
                ('couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Greffons', to='onlineshop.couleur')),
                ('inventaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='order.inventaire', verbose_name='Inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='onlineshop.produit', verbose_name='Produits')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_bis', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('gaf', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.espece')),
                ('portegreffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.portegreffe')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.spec')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.variete')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('nom',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
