# Generated by Django 3.0.14 on 2021-05-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'espece',
                'verbose_name_plural': 'especes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='PorteGreffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'porte-greffe',
                'verbose_name_plural': 'porte-greffes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'specialité',
                'verbose_name_plural': 'specialités',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'variete',
                'verbose_name_plural': 'varietes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='produits/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='onlineshop.Espece')),
                ('portegreffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='onlineshop.PorteGreffe')),
                ('spec', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='onlineshop.Spec')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='onlineshop.Variete')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('nom',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
