# Generated by Django 3.2.13 on 2022-10-25 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'espece',
                'verbose_name_plural': 'especes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='PorteGreffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'porte-greffe',
                'verbose_name_plural': 'porte-greffes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'specialité',
                'verbose_name_plural': 'specialités',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'variete',
                'verbose_name_plural': 'varietes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='ProduitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_bis', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('gaf', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.espece')),
                ('portegreffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.portegreffe')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.spec')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProduitTests', to='onlineshop.variete')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('stock_bis', models.IntegerField(default=0)),
                ('stock_future', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('gaf', models.BooleanField(default=False)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.espece')),
                ('portegreffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.portegreffe')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.spec')),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produits', to='onlineshop.variete')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Greffons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greffons', models.IntegerField(default=0, null=True)),
                ('comm', models.IntegerField(null=True)),
                ('objectif', models.IntegerField(default=0, null=True)),
                ('realise', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('rang', models.IntegerField(default=0, null=True)),
                ('reussi', models.IntegerField(default=0, null=True)),
                ('couleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Greffons', to='onlineshop.couleur')),
            ],
        ),
    ]
