# Generated by Django 3.2.16 on 2023-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcart',
            name='user_text',
            field=models.TextField(default='gregory.faupin'),
            preserve_default=False,
        ),
    ]
