# Generated by Django 3.2.13 on 2022-10-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlineshop', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greffons',
            name='inventaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='order.inventaire'),
        ),
        migrations.AddField(
            model_name='greffons',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='onlineshop.produit'),
        ),
        migrations.AlterIndexTogether(
            name='produittest',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='produit',
            index_together={('id', 'slug')},
        ),
    ]
