# Generated by Django 3.2.16 on 2023-10-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_logcart_user_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcart',
            name='user',
        ),
    ]
