# Generated by Django 3.2.13 on 2022-10-25 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineshop', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
                ('field', models.TextField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField()),
                ('produit', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
                ('field', models.TextField()),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
