# Generated by Django 3.2.16 on 2023-10-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlineshop', '0003_remove_logcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logcart',
            name='user_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
