# Generated by Django 3.2.13 on 2022-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_logcart_logproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcart',
            name='cart',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
