# Generated by Django 3.2.13 on 2022-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0004_logcart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproduit',
            name='order',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logproduit',
            name='user',
            field=models.TextField(),
        ),
    ]
