# Generated by Django 3.2.16 on 2023-02-06 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20230206_1732'),
        ('onlineshop', '0005_auto_20221105_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greffons',
            name='comm',
            field=models.IntegerField(null=True, verbose_name='Pré-Commande'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='greffons',
            field=models.IntegerField(default=0, null=True, verbose_name='Greffons'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='inventaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='order.inventaire', verbose_name='Inventaire'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='objectif',
            field=models.IntegerField(default=0, null=True, verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Greffons', to='onlineshop.produit', verbose_name='Produits'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='rang',
            field=models.IntegerField(default=0, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='realise',
            field=models.IntegerField(default=0, null=True, verbose_name='Réalisés'),
        ),
        migrations.AlterField(
            model_name='greffons',
            name='reussi',
            field=models.IntegerField(default=0, null=True, verbose_name='Reussi'),
        ),
    ]
