# Generated by Django 3.2.16 on 2023-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0006_auto_20230206_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcart',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logcart',
            name='user',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logproduit',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
