# Generated by Django 3.0.14 on 2021-05-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=250)),
                ('prenom', models.CharField(db_index=True, max_length=250)),
                ('adresse', models.TextField(blank=True)),
                ('cp', models.CharField(blank=True, max_length=5)),
                ('ville', models.CharField(blank=True, max_length=250)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('mail', models.CharField(max_length=250)),
                ('commentaire', models.TextField(blank=True)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statut', models.CharField(db_index=True, default='En cours', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='order.Client')),
            ],
        ),
    ]
