# Generated by Django 3.2.13 on 2022-10-25 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlineshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=250)),
                ('prenom', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('societe', models.CharField(blank=True, max_length=250, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.CharField(max_length=250)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 16, 33, 12, 877369))),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, default='En cours', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=250)),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frais', to='order.tva')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('date_update', models.DateTimeField(default=datetime.datetime.now)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_frais', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commandes', to='order.client')),
                ('frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commandes', to='order.frais')),
                ('inventaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Commandes', to='order.inventaire')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commandes', to='order.statut')),
                ('tva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commandes', to='order.tva')),
            ],
        ),
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartdbs', to='order.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cartdbs', to='onlineshop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AccessMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccessModes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
