# Generated by Django 3.0.14 on 2021-05-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0003_produit_available'),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cartdb',
        ),
    ]
