# Generated by Django 3.2.13 on 2022-10-25 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_inventaire_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 16, 39, 39, 456721)),
        ),
    ]
