# Generated by Django 3.2.13 on 2022-11-05 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20221025_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 14, 48, 250056)),
        ),
        migrations.AlterField(
            model_name='logorder',
            name='user',
            field=models.TextField(),
        ),
    ]
