# Generated by Django 3.2.7 on 2022-11-05 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20221105_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 49, 35, 532827)),
        ),
    ]
