# Generated by Django 3.2.5 on 2023-04-22 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230206_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 8, 59, 4, 741643)),
        ),
    ]
