# Generated by Django 3.2.16 on 2023-02-06 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_inventaire_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_valid',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 17, 32, 26, 318950)),
        ),
    ]
