<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-10-10 09:23
=======
# Generated by Django 3.2.5 on 2023-04-22 16:52
>>>>>>> 294f6ffc7e6e2a8bc26c94e3642552afbe2a9b88

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('order', '0008_auto_20230206_1732'),
=======
        ('order', '0008_alter_inventaire_end_date'),
>>>>>>> 294f6ffc7e6e2a8bc26c94e3642552afbe2a9b88
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 9, 23, 21, 23792)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 16, 52, 28, 915371)),
>>>>>>> 294f6ffc7e6e2a8bc26c94e3642552afbe2a9b88
        ),
    ]
