# Generated by Django 3.2.16 on 2023-10-10 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20230206_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 9, 23, 21, 23792)),
        ),
    ]
